theme: pages-themes/hacker@v0.2.0
title: The Projectonist's Homepage
description: Basic description of and docs for the Projector team.
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
